"""
You are given two strings, s and t which only consist of lowercase
letters. t is generated by shuffling the letters in s as well as
potentially adding an additional random character. Return the letter
that was randomly added to t if it exists, otherwise, return ' '.
Note: You may assume that at most one additional character can be added
to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ' '
"""


def spot_the_difference(string_s: str, string_t: str) -> str:
    """Spots which random character has been added to t and returns it"""
    s_dict = set(string_s)
    for char in string_t:
        if char not in s_dict:
            return char

    return ' '


def main():
    """Main function"""
    string_s = input("Enter s: ")
    string_t = input("Enter t: ")

    print(spot_the_difference(string_s, string_t))


if __name__ == "__main__":
    main()
